# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "dotnet" ]
  pull_request:
    branches: [ "dotnet" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Checkout repository
      run: git clone https://github.com/MicrosoftDocs/pipelines-dotnet-core.git
    - name: Restore dependencies
      run: dotnet restore ./pipelines-dotnet-core
    - name: Build
      run: dotnet build --no-restore ./pipelines-dotnet-core
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: SAST
      run: |
        curl -fsSL https://raw.githubusercontent.com/ZupIT/horusec/main/deployments/scripts/install.sh | bash -s latest-beta  
        horusec start -p ./pipelines-dotnet-core -w true -o sarif -O '$(Build.ArtifactStagingDirectory)/sast-results.sarif'
